# -*- coding: utf-8 -*-
"""group_05_plus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111FBd6Cp_C575n3AEM-ZEIbBOcqLi9rj
"""

!sudo apt update
!sudo apt install tesseract-ocr tesseract-ocr-chi-tra

!pip install pytesseract

import pytesseract
from PIL import Image
import cv2

# 開啟圖片
#image = Image.open("你的圖片名稱.png")
image = Image.open("聖誕快樂.png")

text = pytesseract.image_to_string(image, lang='eng+chi_tra', config='--psm 6')
#中英夾雜將lang改成chi_tra+eng，且因文字兩行config那裏要改成6

print("OCR 辨識結果:")
print("-" * 40)
print(text)
