# -*- coding: utf-8 -*-
"""Group_05_Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4g-O7545Ersq0GWsSh3JZ6HoMCucBNm
"""

!sudo apt update
!sudo apt install tesseract-ocr tesseract-ocr-chi-tra

!pip install pytesseract

import pytesseract
from PIL import Image
import cv2

# 開啟圖片
#image = Image.open("你的圖片名稱.png")
image = Image.open("組別英文.png")

text = pytesseract.image_to_string(image, lang='eng', config='--psm 10')
#將lang從chi_tra改成eng就可以辨識英文了

print("OCR 辨識結果:")
print("-" * 40)
print(text)
